{{- if .Values.driverJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: ray-driver-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: driver
          image: {{ .Values.driverJob.image }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: {{ .Values.driverJob.resources.limits.cpu | quote }}
              memory: {{ .Values.driverJob.resources.limits.memory | quote }}
          command:
            - "python"
            - "/app/{{ .Values.driverJob.script }}"
          env:
            - name: RAY_HEAD_SERVICE
              value: "{{ .Values.nameOverride | default .Release.Name }}-head-svc.{{ .Release.Namespace }}.svc:10001"
          {{- with .Values.driverJob.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
