{{- if .Values.driverJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: ray-driver-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: driver
          image: {{ .Values.driverJob.image }}
          command:
            - "python"
            - "/app/{{ .Values.driverJob.script }}"
          env:
            {{- range .Values.driverJob.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
{{- end }}
