ray-cluster:
  image:
    repository: rezabah/rayclusterapp
    tag: "0.1.0"
    pullPolicy: Always
  nameOverride: "rayapp1"
  head:
    # you can find out the Ray version by running this command:
    # docker run --rm rezabah/rayclusterapp:0.1.0 python -c "import ray; print(ray.__version__)"
    rayVersion: 3.0.0.dev0
    image:
      repository: rezabah/rayclusterapp
      tag: "0.1.0"
      pullPolicy: Always
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
        nvidia.com/gpu: 0
    rayStartParams:
      dashboard-host: "0.0.0.0"
      metrics-export-port: "9090"

  worker:
    groupName: workergroup
    replicas: 2
    minReplicas: 1
    maxReplicas: 3
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
        nvidia.com/gpu: 0
    image:
      repository: rezabah/rayclusterapp
      tag: "0.1.0"
      pullPolicy: Always
    rayStartParams: {}

driverJob:
  enabled: true
  image: rezabah/rayclusterapp:0.1.0
  script: train.py
  env:
    - name: USE_GPU
      value: "false"  
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"    
